languageCode = "en-us"
title = "AppCentrix SmartICT"
baseURL = "https://joshuaread/smartict.github.io"
canonifyURLs = true
theme = "hugo-book-master"

[params]
  description = "Documentation for the management and daily use of SmartICT"
  codePenUser = "docread"
